server:
  port: 8082
spring:
  application:
    name: cart-service
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host}:${db.port}/myshop-cart?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: ${db.name}
    password: ${db.pwd}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 15000
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
## mybatis configuration
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # print sql
    map-underscore-to-camel-case: true
    cache-enabled: false  # cache
#mybatis-plus: 
#    configuration:
#      default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#    global-config:
#      db-config:
#        update-strategy: not_null
#        id-type: auto
logging:
  level:
    com.shaoxiaodan: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

apidocs:
  info:
    title: Cloud-MyShop Api docs
    description: "shopping cart service API doc"
    version: v1.0.0
  contact:
    name: Xiaodan Shao(Daniel)
    email: shaoxiaodan1009@gmail.com
    url: https://www.shaoxiaodan.com.cn